### ISSUE TITLE
Secret unveiled

### ISSUE THREAD

**Issue by Dynnammo** [OpenSourcePolitics/decidim-module-friendly_signup#1]
We just received a Git Guardian alert concerning this commit [95b9147](https://github.com/OpenSourcePolitics/decidim-module-friendly_signup/commit/95b91474ff95d4e50e9cb52613713ef077c0f353#diff-6728949a78c2afe7bbab44a6fba7d578df36a3f5ce3a6f9ced0d0d058032c25cR12) , line 12.

Is this a real secret or is it fake ?

**Comment by microstudi** [comment]
don't worry, GitGuardian is concern about anything that looks like a md5, sha1, etc string. There's no secrets here
