### ISSUE TITLE
Link in the registration confirmation email

### ISSUE THREAD

**Issue by luciegrau** [OpenSourcePolitics/decidim-module-friendly_signup#10]
**Description of the bug**
When I receive the registration confirmation email, the link in the email does not redirect me to the platform as expected. Instead I have a warning the the url is no valid (http:///friendly_signup/confirmation_codes?confirmation_token=y52EEQ64-nBPfSWdw4AQ).

**To reproduce**
1. Register on the platform 
2. Receive and open the registration confirmation email
3. Click on the link in the body of the email
4. You are redirected to a warning that the url is not valid

**Screenshots** 
Link displayed in the registration confirmation email :
<img width="466" alt="Capture d’écran 2022-10-05 à 15 37 57" src="https://user-images.githubusercontent.com/87868063/194075438-82fb6ae9-c5e8-434c-8318-c9788e078bb1.png">

When clicking on the link : 
<img width="1301" alt="Capture d’écran 2022-10-05 à 15 40 23" src="https://user-images.githubusercontent.com/87868063/194075931-7156698e-8add-4ea0-b34f-65ef2ad81b02.png">

**Comment by Quentinchampenois** [comment]
Hello nice catch ! We will fix this link asap
