### ISSUE TITLE
Number of requests too high to validate the form

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim-module-friendly_signup#17]
When I connect to the platform to register, the friendly_sign_up makes a lot of back-end calls. 

The number of these requests seems to be related to the number of characters plus ten.

For example, for a name of 10 characters, an e-mail of 20 characters and a password of 10 characters, the number of requests issued is 60 at least.

<img width="1687" alt="Capture d’écran 2023-01-19 à 11 11 27" src="https://user-images.githubusercontent.com/20232956/213415213-89425526-03e7-4a66-be2f-dd1020b527c2.png">

**Comment by Quentinchampenois** [comment]
Reduced by #20, do not hesitate to reopen issue if needed
